###
# MAIN CONFIGURATION FILE FOR FIREHOSE
# DO NOT EDIT THIS FILE!
#
# Make changes in separate environment files (dev.exs, prod.exs).
###

use Mix.Config

# Log info messages
config :logger, level: :info

# Firehose Discord client configuration
config :firehose,
  # Compress connection?
  # Note: default is false
  discord_compress: false,

  # Discord websocket encoding (:etf or :json)
  # Note: default is :etf
  discord_encoding: :etf,

  # Total shards across the whole bot (not just this node)
  discord_shards_count: 1,

  # Discord shard IDs to spawn (zero-indexed)
  discord_shards: 0 # 0..15

  # Discord token
  # discord_token: "Bot ..."

# Firehose Nozzle configuration
config :firehose,
  # Nozzle to use (:amqp)
  # Note: :amqp is forced until more Nozzles are created
  nozzle: :amqp,

  # AMQP nozzle connection options
  # See https://hexdocs.pm/amqp/AMQP.Connection.html#open/1
  nozzle_amqp_options: "amqp://guest:guest@localhost",

  # Amount of nozzles to spawn (note: nozzles are shared)
  nozzle_count: 3

# UNTESTED: Firehose Nozzle autoscaling configuration
config :firehose,
  # Enable autoscaling?
  autoscale_enabled: false,

  # Max Nozzles to spawn
  # Note: minimum is `nozzle_count`, default is `nozzle_count * 2`
  autoscale_max: 6,

  # Autoscale conditions
  # See README.md
  autoscale_conditions: [
    {:up, queued_events: {:gt, 1000}},
    {:down, queued_events: {:lt, 100}},
    {:notify, queued_events: {:gt, 600}}
  ]

  # Optional Slack webhook notification URLs (add /slack to Discord webhook URLs)
  # autoscale_webhooks: [
  #   "https://discordapp.com/api/webhooks/.../.../slack"
  # ]

# Import environment-specific configuration
import_config "#{Mix.env}.exs"
